version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 455573923271.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - echo Building Docker image...
      - docker build -t devops-lab5-app:latest .
      - docker tag devops-lab5-app:latest 455573923271.dkr.ecr.ap-south-1.amazonaws.com/devops-lab5-app:latest

  post_build:
    commands:
      - echo Pushing Docker image to Amazon ECR...
      - docker push 455573923271.dkr.ecr.ap-south-1.amazonaws.com/devops-lab5-app:latest
      - echo Build completed successfully.